### ISSUE TITLE
0demo

### ISSUE THREAD

**Issue by trtstm** [cadenzr/cadenzr#9]
Should it be in the source code?

**Comment by DenBeke** [comment]
It contains an mp3 file needed for the scan/api tests and for testing the prober.

**Comment by trtstm** [comment]
ok, but it should be moved to its own directory when testing has been cleaned up?

**Comment by DenBeke** [comment]
How do you mean?

**Comment by trtstm** [comment]
Why should there be a mp3 file that will be used by tests in the user's media directory :p.

**Comment by DenBeke** [comment]
Because it's easier to test like this ;)
